#!/usr/bin/env python3
"""
Batch-16 Speedup Test for Normal and Anomaly Scenarios

Tests the speedup of batch_size=16 vs single request mode,
comparing Baseline vs Adaptive TTL.

Usage:
    python test_batch16_speedup.py --mode baseline
    python test_batch16_speedup.py --mode anomaly
"""

import sys
sys.path.insert(0, '.')

import os
import json
import tempfile
import random
import argparse
from typing import List, Dict, Any, Tuple
from itertools import product

from simulator import KVCacheSimulator
from simulator.timing import HardwareConfig, TimingCalculator


HARDWARE_CONFIG = {
    'prefill_latency_per_token_ms': 2.0,
    'decode_latency_per_token_ms': 20.0,
    'ttft_overhead_ms': 100.0,
    'queue_delay_per_request_ms': 50.0,
    'bytes_per_token': 512.0,
    'h2d_bandwidth_GBps': 32.0,
    'bandwidth_efficiency': 0.85,
    'h2d_overhead_us': 6.67,
    'd2h_overhead_us': 4.0,
    'memory_bandwidth_GBps': 64.0,
}


# Best configurations from sweep tests
BEST_CONFIGS = [
    {'name': 'Best-1', 'l1': 6000, 'programs': 80, 'turns': 15, 'prefill': 200, 'tool_time': 2.0},
    {'name': 'Best-2', 'l1': 6000, 'programs': 70, 'turns': 15, 'prefill': 200, 'tool_time': 2.0},
    {'name': 'Best-3', 'l1': 8000, 'programs': 80, 'turns': 15, 'prefill': 200, 'tool_time': 2.0},
    {'name': 'Best-4', 'l1': 8000, 'programs': 70, 'turns': 15, 'prefill': 200, 'tool_time': 2.0},
    {'name': 'Best-5', 'l1': 8000, 'programs': 50, 'turns': 15, 'prefill': 200, 'tool_time': 3.0},
]


def generate_requests(
    programs: int, turns: int, prefill: int, tool_time: float,
    jps: float = 0.0, arrival_mode: str = 'simultaneous', seed: int = 42
) -> List[Dict]:
    """Generate requests for simulation with proper program interleaving.
    
    In real scenarios, programs interleave - a program doesn't complete all its
    turns before other programs start. We use a Poisson process to model when
    each program's first turn arrives. Subsequent turns are generated by the
    simulator's _on_request_complete based on program_max_turns.
    
    Only turn 0 requests are generated here. The simulator handles generating
    subsequent turns based on tool execution times.
    """
    random.seed(seed)
    
    def calc_turn_tokens(turn):
        if turn == 0: return prefill * 5
        elif turn == 1: return prefill * 3
        elif turn == 2: return prefill * 2
        else: return prefill
    
    # Generate program data for turn 0 (subsequent turns handled by simulator)
    program_data = []
    for prog_idx in range(programs):
        program_id = f'prog_{prog_idx:03d}'
        accumulated = []
        
        # Generate turn 0 tokens
        nt = calc_turn_tokens(0)
        new_tokens = list(range(prog_idx * 1000000,
                               prog_idx * 1000000 + nt))
        tokens = new_tokens  # Turn 0 has no prefix
        
        program_data.append({
            'program_id': program_id,
            'tokens': tokens,
            'input_len': len(tokens),
            'extra_key': program_id,
        })
    
    # Assign arrival times based on arrival mode
    requests = []
    
    if arrival_mode == 'simultaneous':
        # Interleave programs: each program's first turn arrives at a different time
        # This models realistic arrival patterns where programs overlap
        if jps <= 0:
            jps = 1.0  # Default to 1 job per second if not specified
        
        for prog_idx, prog in enumerate(program_data):
            # Stagger program start times using Poisson process
            arrival_time = prog_idx * random.expovariate(jps)
            
            requests.append({
                'rid': f'{prog["program_id"]}_turn_0',
                'program_id': prog['program_id'],
                'turn_index': 0,
                'token_ids': prog['tokens'],
                'input_len': prog['input_len'],
                'output_len': 64,
                'arrival_time': arrival_time,
                'is_tool_call': True,  # All turns except last generate next turn
                'tool_name': 'tool_0',
                'extra_key': prog['extra_key'],
                'ttl_sec': None,
                'actual_tool_duration': tool_time,
                'max_turns': turns,  # Tell simulator how many turns this program has
            })
    
    elif arrival_mode == 'batch_poisson':
        if jps > 0:
            mean_inter_arrival = 1.0 / jps
        else:
            mean_inter_arrival = float('inf')
        
        current_time = 0.0
        for prog_idx, prog in enumerate(program_data):
            requests.append({
                'rid': f'{prog["program_id"]}_turn_0',
                'program_id': prog['program_id'],
                'turn_index': 0,
                'token_ids': prog['tokens'],
                'input_len': prog['input_len'],
                'output_len': 64,
                'arrival_time': current_time,
                'is_tool_call': True,
                'tool_name': 'tool_0',
                'extra_key': prog['extra_key'],
                'ttl_sec': None,
                'actual_tool_duration': tool_time,
                'max_turns': turns,
            })
            # Stagger next program
            if jps > 0:
                current_time += random.expovariate(jps)
    
    return requests


def apply_exceptions(
    requests: List[Dict],
    exception_type: str,
    rate: float,
    base_duration: float = 2.0,
    seed: int = 123
) -> List[Dict]:
    """Apply tool exceptions to requests."""
    random.seed(seed)
    modified = []

    for req in requests:
        if not req['is_tool_call']:
            modified.append(req.copy())
            continue

        new_req = req.copy()
        if random.random() < rate:
            if exception_type == 'timeout':
                new_req['actual_tool_duration'] = base_duration * 5.0
            elif exception_type == 'retry':
                new_req['actual_tool_duration'] = base_duration * 2.0
            elif exception_type == 'hang':
                new_req['actual_tool_duration'] = base_duration * 10.0
            elif exception_type == 'early_return':
                new_req['actual_tool_duration'] = base_duration * 0.1
            elif exception_type == 'timeout_extreme':
                new_req['actual_tool_duration'] = base_duration * 20.0
        else:
            new_req['actual_tool_duration'] = base_duration
        modified.append(new_req)

    return modified


def create_simulator(requests, enable_ttl, l1, l2, tool_time=2.0, 
                     history_threshold=3, batch_size=16, enable_batch=True):
    """Create simulator with configurable batch size."""
    with tempfile.NamedTemporaryFile(mode='w', suffix='.jsonl', delete=False) as f:
        for req in requests:
            f.write(json.dumps(req) + '\n')
        temp_path = f.name
    try:
        hw = HardwareConfig(**HARDWARE_CONFIG)
        timing_calc = TimingCalculator(hw=hw)

        sim = KVCacheSimulator(
            cache_capacity=l1, l2_capacity=l2, l2_enabled=l2 > 0,
            l2_reload_penalty=0.3,
            default_ttl=5.0, min_ttl=0.5, max_ttl=60.0,
            enable_ttl=enable_ttl, enable_adaptive_ttl=enable_ttl,
            simulation_mode='event_driven', poisson_lambda=1.0 / 0.3,
            tool_execution_time=tool_time, random_seed=42,
            hardware_config=hw, timing_config=timing_calc, write_policy='write_through',
            history_threshold=history_threshold, ttl_grid_points=50,
        )
        sim.load_requests(temp_path)
        for pid in sim.scheduler.program_total_turns:
            sim.scheduler.program_total_turns[pid] = 999
        sim.run(enable_batch=enable_batch, batch_size=batch_size, verbose=False)
        return sim
    finally:
        os.unlink(temp_path)


def analyze_result(sim):
    """Analyze simulation result."""
    log = sim.scheduler.scheduling_log
    if not log:
        return {'time': 0, 'ttl_hits': 0, 'l1_hits': 0, 'l2_hits': 0, 'misses': 0}

    ttl_hits = sum(1 for e in log if e['hit_type'] == 'TTL')
    l1_hits = sum(1 for e in log if e['hit_type'] == 'L1')
    l2_hits = sum(1 for e in log if e['hit_type'] == 'L2')
    misses = sum(1 for e in log if e['hit_type'] == 'L1+L2 Miss')
    total_time = log[-1]['finish_time'] if log else 0

    total_prefill_ms = sum(e.get('prefill_ms', 0) for e in log)
    total_queue_ms = sum(e.get('queue_wait_ms', 0) for e in log)

    return {
        'time': total_time,
        'ttl_hits': ttl_hits, 'l1_hits': l1_hits, 'l2_hits': l2_hits, 'misses': misses,
        'prefill_s': total_prefill_ms / 1000,
        'queue_s': total_queue_ms / 1000,
    }


def test_scenario(config: Dict, scenario_name: str, exception_type: str, rate: float, 
                  seed: int = 42, batch_size: int = 16, mode: str = 'batch') -> Dict[str, Any]:
    """Test a single scenario for a configuration."""
    l1 = config['l1']
    l2 = int(l1 * 1.5)
    base_tool_time = config['tool_time']

    # Generate base requests
    requests = generate_requests(
        config['programs'], config['turns'], config['prefill'], base_tool_time,
        jps=0.0, arrival_mode='simultaneous', seed=seed
    )

    # Apply exceptions
    if exception_type:
        requests = apply_exceptions(requests, exception_type, rate, base_tool_time, seed=seed + 100)

    # Calculate actual average tool time
    tool_times = [r['actual_tool_duration'] for r in requests if r['is_tool_call']]
    avg_tool_time = sum(tool_times) / len(tool_times) if tool_times else base_tool_time

    # Baseline
    print(f"  [{scenario_name}] Baseline (mode={mode})...", end=" ", flush=True)
    enable_batch = (mode == 'batch')
    sim_bl = create_simulator(requests, False, l1, l2, avg_tool_time, 
                             batch_size=batch_size, enable_batch=enable_batch)
    r_bl = analyze_result(sim_bl)
    print(f"{r_bl['time']:.1f}s")

    # TTL
    print(f"  [{scenario_name}] AdaptiveTTL (mode={mode})...", end=" ", flush=True)
    sim_ttl = create_simulator(requests, True, l1, l2, avg_tool_time, 
                              batch_size=batch_size, enable_batch=enable_batch)
    r_ttl = analyze_result(sim_ttl)
    print(f"{r_ttl['time']:.1f}s")

    speedup = r_bl['time'] / r_ttl['time'] if r_ttl['time'] > 0 else 0

    return {
        'config_name': config['name'],
        'l1': l1,
        'programs': config['programs'],
        'turns': config['turns'],
        'scenario': scenario_name,
        'exception_type': exception_type,
        'rate': rate,
        'avg_tool_time': avg_tool_time,
        'baseline': r_bl,
        'ttl': r_ttl,
        'speedup': speedup,
        'batch_size': batch_size,
        'mode': mode,
    }


def run_mode_comparison_tests(batch_size: int = 16):
    """Run tests comparing single mode vs batch mode."""
    print("=" * 100)
    print(f"MODE COMPARISON TEST (batch_size={batch_size})")
    print("=" * 100)
    print()
    
    # Use Best-1 config
    config = BEST_CONFIGS[0]
    l1 = config['l1']
    l2 = int(l1 * 1.5)
    base_tool_time = config['tool_time']
    
    requests = generate_requests(
        config['programs'], config['turns'], config['prefill'], base_tool_time,
        jps=0.0, arrival_mode='simultaneous', seed=42
    )
    
    results = []
    
    for mode in ['single', 'batch']:
        print("-" * 80)
        print(f"Mode: {mode.upper()} (batch_size={'inf' if mode == 'single' else batch_size})")
        print("-" * 80)
        
        enable_batch = (mode == 'batch')
        
        # Baseline
        print(f"  Baseline...", end=" ", flush=True)
        sim_bl = create_simulator(requests.copy(), False, l1, l2, base_tool_time, 
                                batch_size=batch_size, enable_batch=enable_batch)
        r_bl = analyze_result(sim_bl)
        print(f"Time={r_bl['time']:.1f}s TTL={r_bl['ttl_hits']} L1={r_bl['l1_hits']} L2={r_bl['l2_hits']} Miss={r_bl['misses']}")
        
        # TTL
        print(f"  TTL...", end=" ", flush=True)
        sim_ttl = create_simulator(requests.copy(), True, l1, l2, base_tool_time, 
                                  batch_size=batch_size, enable_batch=enable_batch)
        r_ttl = analyze_result(sim_ttl)
        print(f"Time={r_ttl['time']:.1f}s TTL={r_ttl['ttl_hits']} L1={r_ttl['l1_hits']} L2={r_ttl['l2_hits']} Miss={r_ttl['misses']}")
        
        ttl_speedup = r_bl['time'] / r_ttl['time'] if r_ttl['time'] > 0 else 0
        
        results.append({
            'mode': mode,
            'baseline': r_bl,
            'ttl': r_ttl,
            'ttl_speedup': ttl_speedup,
        })
        
        print()
    
    # Summary
    print("=" * 100)
    print("SUMMARY")
    print("=" * 100)
    print()
    print(f"{'Mode':<10} | {'Baseline':>12} | {'TTL':>12} | {'TTL Speedup':>12} | {'TTL':>5} | {'L1':>5} | {'Miss':>5}")
    print("-" * 80)
    
    for r in results:
        print(f"{r['mode']:<10} | {r['baseline']['time']:>10.1f}s | {r['ttl']['time']:>10.1f}s | {r['ttl_speedup']:>10.2f}x | {r['ttl']['ttl_hits']:>5} | {r['ttl']['l1_hits']:>5} | {r['ttl']['misses']:>5}")
    
    # Calculate batch vs single speedup
    single_bl_time = results[0]['baseline']['time']
    batch_bl_time = results[1]['baseline']['time']
    batch_speedup = single_bl_time / batch_bl_time if batch_bl_time > 0 else 0
    
    print()
    print(f"Batch Mode vs Single Mode Speedup (Baseline): {batch_speedup:.2f}x")
    
    return results


def run_anomaly_tests(batch_size: int = 16):
    """Run anomaly scenario tests."""
    print("=" * 100)
    print(f"ANOMALY SCENARIO TEST (batch_size={batch_size})")
    print("=" * 100)
    print()

    scenarios = [
        ('正常 (无异常)', None, 0.0),
        ('超时 30%', 'timeout', 0.30),
        ('重试 30%', 'retry', 0.30),
        ('挂起 10%', 'hang', 0.10),
        ('提前返回 30%', 'early_return', 0.30),
    ]

    all_results = []

    for config in BEST_CONFIGS:
        print("-" * 100)
        print(f"CONFIG: {config['name']} (L1={config['l1']}, P={config['programs']}, T={config['turns']})")
        print("-" * 100)

        for scenario_name, exception_type, rate in scenarios:
            result = test_scenario(config, scenario_name, exception_type, rate, 
                                  batch_size=batch_size, mode='batch')
            all_results.append(result)
            speedup_str = f"{result['speedup']:.2f}x" if result['speedup'] >= 1 else f"{-1/result['speedup']:.2f}x慢"
            print(f"  => Speedup: {speedup_str} | Miss_BL={result['baseline']['misses']} Miss_TTL={result['ttl']['misses']}")
        print()

    # Summary
    print("=" * 100)
    print("SUMMARY: Anomaly Scenarios")
    print("=" * 100)
    print()

    print(f"{'场景':<20} | {'Baseline':>10} | {'TTL':>10} | {'加速':>8} | {'Miss减少':>8}")
    print("-" * 70)

    for r in all_results:
        speedup_str = f"{r['speedup']:.2f}x" if r['speedup'] >= 1 else f"{-1/r['speedup']:.2f}x慢"
        miss_reduction = r['baseline']['misses'] - r['ttl']['misses']
        miss_str = f"{miss_reduction:+d}" if miss_reduction != 0 else "0"
        print(f"{r['scenario']:<20} | {r['baseline']['time']:>8.1f}s | {r['ttl']['time']:>8.1f}s | {speedup_str:>8} | {miss_str:>8}")

    return all_results


def main():
    parser = argparse.ArgumentParser(description="Batch-16 Speedup Test")
    parser.add_argument('--mode', type=str, default='comparison',
                       choices=['comparison', 'anomaly'],
                       help='Test mode')
    parser.add_argument('--batch-size', type=int, default=16,
                       help='Batch size for simulation (default: 16)')
    args = parser.parse_args()

    print("=" * 100)
    print(f"Batch Size = {args.batch_size}")
    print("=" * 100)
    print()

    if args.mode == 'comparison':
        run_mode_comparison_tests(batch_size=args.batch_size)
    elif args.mode == 'anomaly':
        run_anomaly_tests(batch_size=args.batch_size)


if __name__ == "__main__":
    main()
